# Generated by Django 5.2.1 on 2025-06-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callrecording',
            name='filename',
        ),
        migrations.AddField(
            model_name='callrecording',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callrecording',
            name='uploaded_at',
            field=models.DateTimeField(),
        ),
    ]
