# Generated by Django 5.2.4 on 2025-07-05 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0002_uploadfile_delete_uploadedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='note',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='user',
        ),
        migrations.CreateModel(
            name='UploadGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='CRU.uploadgroup'),
            preserve_default=False,
        ),
    ]
