# Generated by Django 5.2.4 on 2025-07-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRU', '0003_remove_uploadfile_created_at_remove_uploadfile_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadgroup',
            name='note',
            field=models.TextField(),
        ),
    ]
